<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Cash Flow Statement</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #1a1a1a;
            text-transform: uppercase;
        }

        .header h2 {
            margin: 5px 0 0;
            font-size: 16px;
            color: #666;
            font-weight: normal;
        }

        .meta {
            margin-bottom: 30px;
        }

        .meta table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta td {
            padding: 5px;
        }

        .meta .label {
            font-weight: bold;
            color: #666;
            width: 120px;
        }

        .section-title {
            font-size: 14px;
            font-weight: bold;
            text-transform: uppercase;
            margin-bottom: 10px;
            color: #444;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }

        table.financials {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table.financials th,
        table.financials td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }

        table.financials th {
            background-color: #f9f9f9;
            font-weight: bold;
        }

        table.financials td.amount {
            text-align: right;
        }

        .row-summary td {
            padding: 15px 8px;
            font-size: 14px;
            font-weight: bold;
        }

        .text-success {
            color: #198754;
        }

        .text-danger {
            color: #dc3545;
        }

        .text-primary {
            color: #0d6efd;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #aaa;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Cash Flow Statement</h1>
        <h2>{{ $selectedDuka ? $selectedDuka->name : 'All Allocations' }}</h2>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td class="label">Period:</td>
                <td>{{ $start->format('d M Y') }} — {{ $end->format('d M Y') }}</td>
            </tr>
            <tr>
                <td class="label">Generated On:</td>
                <td>{{ now()->format('d M Y H:i:s') }}</td>
            </tr>
            <tr>
                <td class="label">Generated By:</td>
                <td>{{ auth()->user()->name }}</td>
            </tr>
        </table>
    </div>

    <div class="content">
        <!-- Summary Section -->
        <div class="section-title">Financial Summary</div>
        <table class="financials" style="border: 1px solid #eee;">
            <tr class="row-summary">
                <td>Total Inflow</td>
                <td class="amount text-success">+ {{ number_format($totalIncome) }} TSH</td>
            </tr>
            <tr class="row-summary">
                <td>Total Outflow</td>
                <td class="amount text-danger">- {{ number_format($totalExpense) }} TSH</td>
            </tr>
            <tr class="row-summary" style="background-color: #f0f0f0; border-top: 2px solid #ccc;">
                <td>Net Cash Position</td>
                <td class="amount {{ $netCashFlow >= 0 ? 'text-primary' : 'text-danger' }}">
                    {{ number_format($netCashFlow) }} TSH
                </td>
            </tr>
        </table>

        <!-- Transactions Table -->
        <div class="section-title" style="margin-top: 30px;">Transaction History</div>
        <table class="financials">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th style="text-align: right;">Inflow</th>
                    <th style="text-align: right;">Outflow</th>
                </tr>
            </thead>
            <tbody>
                @forelse($transactions as $trx)
                <tr>
                    <td>{{ $trx->transaction_date->format('d M, Y') }}</td>
                    <td>{{ strtoupper($trx->category) }}</td>
                    <td>{{ $trx->description }}</td>
                    <td class="amount text-success">
                        {{ $trx->type === 'income' ? number_format($trx->amount) : '' }}
                    </td>
                    <td class="amount text-danger">
                        {{ $trx->type === 'expense' ? number_format($trx->amount) : '' }}
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="5" style="text-align: center; color: #999; font-style: italic; padding: 20px;">No transactions found for this period.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by StockFlow KP
    </div>
</body>

</html>