<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Profit & Loss Statement</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #1a1a1a;
            text-transform: uppercase;
        }

        .header h2 {
            margin: 5px 0 0;
            font-size: 16px;
            color: #666;
            font-weight: normal;
        }

        .meta {
            margin-bottom: 30px;
        }

        .meta table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta td {
            padding: 5px;
        }

        .meta .label {
            font-weight: bold;
            color: #666;
            width: 120px;
        }

        .section-title {
            font-size: 14px;
            font-weight: bold;
            text-transform: uppercase;
            margin-bottom: 10px;
            color: #444;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }

        table.financials {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table.financials th,
        table.financials td {
            padding: 8px;
            text-align: left;
        }

        table.financials td.amount {
            text-align: right;
        }

        .row-total {
            font-weight: bold;
            background-color: #f9f9f9;
        }

        .row-subtotal {
            color: #555;
        }

        .row-gross {
            font-weight: bold;
            font-size: 14px;
            background-color: #eef;
        }

        .row-net {
            font-weight: bold;
            font-size: 16px;
            color: white;
            background-color: #333;
        }

        .row-net td {
            padding: 15px 8px;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #aaa;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }

        .text-success {
            color: #198754;
        }

        .text-danger {
            color: #dc3545;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Profit & Loss Statement</h1>
        <h2>{{ $selectedDuka ? $selectedDuka->name : 'All Allocations' }}</h2>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td class="label">Period:</td>
                <td>{{ $start->format('d M Y') }} — {{ $end->format('d M Y') }}</td>
            </tr>
            <tr>
                <td class="label">Generated On:</td>
                <td>{{ now()->format('d M Y H:i:s') }}</td>
            </tr>
            <tr>
                <td class="label">Generated By:</td>
                <td>{{ auth()->user()->name }}</td>
            </tr>
        </table>
    </div>

    <div class="content">
        <!-- Revenue Section -->
        <div class="section-title">1. Operating Revenue</div>
        <table class="financials">
            <tr>
                <td>Total Sales Revenue</td>
                <td class="amount">{{ number_format($totalRevenue) }} TSH</td>
            </tr>
            <tr>
                <td>Cost of Goods Sold (COGS)</td>
                <td class="amount text-danger">- {{ number_format($cogs) }} TSH</td>
            </tr>
            <tr class="row-gross">
                <td>Gross Profit</td>
                <td class="amount">{{ number_format($grossProfit) }} TSH</td>
            </tr>
        </table>

        <!-- Expenses Section -->
        <div class="section-title">2. Operating Expenses</div>
        <table class="financials">
            @forelse($expenses as $expense)
            <tr>
                <td>{{ ucwords(str_replace('_', ' ', $expense->category)) }}</td>
                <td class="amount">{{ number_format($expense->total) }} TSH</td>
            </tr>
            @empty
            <tr>
                <td colspan="2" style="text-align: center; color: #999; font-style: italic;">No expenses recorded for this period.</td>
            </tr>
            @endforelse
            <tr class="row-total">
                <td>Total Operating Expenses</td>
                <td class="amount text-danger">- {{ number_format($totalExpenses) }} TSH</td>
            </tr>
        </table>

        <!-- Net Profit Section -->
        <div style="margin-top: 30px;">
            <table class="financials">
                <tr class="row-net">
                    <td style="color: white;">NET PROFIT / (LOSS)</td>
                    <td class="amount" style="color: white;">{{ number_format($netProfit) }} TSH</td>
                </tr>
            </table>
        </div>

        <!-- Inventory Valuation (Informational) -->
        <div class="section-title" style="margin-top: 40px;">3. Inventory Valuation (Informational)</div>
        <table class="financials">
            <tr>
                <td>Total Stock Value (Cost Price)</td>
                <td class="amount">{{ number_format($totalStockBuyingValue) }} TSH</td>
            </tr>
            <tr>
                <td>Potential Revenue (Selling Price)</td>
                <td class="amount">{{ number_format($totalStockSellingValue) }} TSH</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        Generated by StockFlow KP
    </div>
</body>

</html>